version: '3'

services:
    server: # service name
      container_name: server
      build:
        context: .
        dockerfile: ./build/Dockerfile
      volumes:
        - ./:/go/src/github.com/go-todo
      tty: true   # make containers persistent
      env_file:
        - ./build/.go_env
      environment:
        - TZ=Asia/Tokyo
      ports:
        - "8000:8000"
    db:
      image: postgres:15
      container_name: postgres
      ports:
        - 5432:5432
      volumes:
        - ./postgresql/data:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD:db_pass
        POSTGRES_DB:todolist
        LANG:ja_JP.utf8
        TZ:Asia/Tokyo


