version: '3'

services:
    server: # service name
      container_name: server
      build:
        context: .
        dockerfile: ./build/Dockerfile
      volumes:
        - ./:/go/src/github.com/go-todo
      tty: true   # make containers persistent
      env_file:
        - ./build/.go_env
      environment:
        - TZ=Asia/Tokyo
        - DB_HOSTNAME=postgres
        - DB_USERNAME=postgres
        - DB_PASSWORD=passw0rd
        - DB_PORT=5432
      ports:
        - "8000:8000"
    db:
      image: postgres:14
      container_name: postgres
      env_file: ./.env
      ports:
        - 5432:5432
      volumes:
        - ./postgresql/data:/var/lib/postgresql/data
      environment:  # psql -h localhost -U postgres #psqlで接続確認
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - LANG=ja_JP.utf8
        - TZ=Asia/Tokyo
      restart: always


